### ISSUE TITLE
Improve folder structure 

### ISSUE THREAD

**Issue by deepak-chawla** [abhinavkashyap061/todolist#11]
make the code clean by separeting models, routes and controller for better code understanding.

explained here:
https://medium.com/@abhijeetgurle/file-structure-of-node-js-and-express-application-4d9fb66c8d68

**Comment by abhinavkashyap061** [comment]
Hey @deepak-chawla  👋, Thanks for considering contributing to my project

- Okay. I am assigning you this task 👍

Happy Hacking 🚀
