### ISSUE TITLE
button css

### ISSUE THREAD

**Issue by BrunoLagoa** [abhinavkashyap061/todolist#12]
the + icon on the button is not center aligned correctly. If that makes sense to you, you can assign me that adjustment. Thanks.

**Comment by abhinavkashyap061** [comment]
Hey @BrunoLagoa  👋, Thanks for considering contributing to my project

- please check the live app again, is it having the same issue? 

Happy Hacking 🚀

**Comment by BrunoLagoa** [comment]
@abhinavkashyap061 OK, it's been updated.

another suggestion would be:
  - leave the button with the same height as the input;
  - leave a space between them or remove the rounding where they meet.

what do you think?

<img width="706" alt="Captura de Tela 2022-10-10 às 15 04 29" src="https://user-images.githubusercontent.com/3878945/194927874-2b9fcec8-49a0-499c-97fe-c7e1f54d6c46.png">

**Comment by abhinavkashyap061** [comment]
Yes, that's a very amazing suggestion @BrunoLagoa . I am assigning you this task 👍

**Comment by Kritika30032002** [comment]
May I contribute to this?

**Comment by BrunoLagoa** [comment]
adjustment has already been made in
https://github.com/abhinavkashyap061/todolist/pull/23
