### ISSUE TITLE
Readme link live preview

### ISSUE THREAD

**Issue by BrunoLagoa** [abhinavkashyap061/todolist#13]
It would be nice to open a new browser tab when clicking on live project, so the user wouldn't leave your project on github. If that makes sense to you, you can assign me that adjustment. Thanks

**Comment by abhinavkashyap061** [comment]
Hey @ 👋, Thanks for considering contributing to my project

- ok, i am assigning you this task 👍

Happy Hacking 🚀

**Comment by BrunoLagoa** [comment]
Hi, I'm going to need to close this issue, unfortunately github is not able to do that.

We tried with:
_config.yml
     kramdown

####<a href="https://todolist-abhinavkashyap061.herokuapp.com" target="_blank">🎨 Click here for the live demo!</a>

#### [🎨 Click here for the live demo!](https://todolist-abhinavkashyap061.herokuapp.com){:target="_blank" rel="noopener"}

all github, disabled. =(

But I can still help in updating the Readme with other contributions. what do you think?
