### ISSUE TITLE
Make the footer stick to the bottom of the page

### ISSUE THREAD

**Issue by ArkaPrabhaChowdhury** [abhinavkashyap061/todolist#15]
The footer is moving up when I scroll down on my mobile phone. I can fix the footer to the bottom or reduce the margins.

**Comment by Kritika30032002** [comment]
Assign this to me...

**Comment by RegishShrestha** [comment]
Can u assign me this issue?

**Comment by Kritika30032002** [comment]
> Assign this to me...

@abhinavkashyap061
