### ISSUE TITLE
footer less visible

### ISSUE THREAD

**Issue by smrkarkii** [abhinavkashyap061/todolist#16]
The links in footer section is not visible enough.  Please assign it to me under hacktoberfest.

![Screenshot 2022-10-10 211707](https://user-images.githubusercontent.com/58778838/194902958-0d895c2b-26fa-4add-9dba-d13d428c41c7.png)

**Comment by abhinavkashyap061** [comment]
Hey @smrkarkii  👋, Thanks for considering contributing to my project

- ok i am assigning you this task 👍

Happy Hacking 🚀
