### ISSUE TITLE
Improvement in the day section

### ISSUE THREAD

**Issue by palsiddharth091** [abhinavkashyap061/todolist#17]
<img width="534" alt="Screenshot 2022-10-10 at 10 40 06 PM" src="https://user-images.githubusercontent.com/70902237/194919624-e842920c-efc3-49d1-b4f3-07f554c33d5c.png">

The text "Today" in this section does not give a user experience.  In this section I would like to add a real time clock and the day. It will look better. 

@abhinavkashyap061 Please assign me this task.

**Comment by abhinavkashyap061** [comment]
Hey @palsiddharth091  👋, Thanks for considering contributing to my project

- Okay sure, i am assigning you this task 👍

Happy Hacking 🚀
