### ISSUE TITLE
Improvement in responsiveness is needed for mobile view.

### ISSUE THREAD

**Issue by palsiddharth091** [abhinavkashyap061/todolist#18]
<img width="267" alt="Screenshot 2022-10-10 at 10 45 13 PM 1" src="https://user-images.githubusercontent.com/70902237/194920371-56cdcf3d-fdb4-414a-b2ca-153c4b31b723.png">
The mobile view of this application is not responsive. @abhinavkashyap061 please assign me this issue so that I can make the app responsive and more user friendly.

**Comment by abhinavkashyap061** [comment]
Hey @palsiddharth091  👋, Thanks for considering contributing to my project

- Okay , i am assigning you this task 👍

Happy Hacking 🚀

**Comment by Aakashbansal837** [comment]
Hey @palsiddharth091 , @abhinavkashyap061 

are you guys working on this one? If not then please assign it to me. Thanks

**Comment by palsiddharth091** [comment]
> Hey @palsiddharth091 , @abhinavkashyap061 
> 
> are you guys working on this one? If not then please assign it to me. Thanks

Yes. I am working on it.

**Comment by Aakashbansal837** [comment]
@palsiddharth091 👍

**Comment by abhinavkashyap061** [comment]
@palsiddharth091 amazing work mate ❤

**Comment by palsiddharth091** [comment]
Thank you :)
