### ISSUE TITLE
[Feat.] authorization and authentication

### ISSUE THREAD

**Issue by BiswajitSahoo-tech** [abhinavkashyap061/todolist#2]
Hi, @abhinavkashyap061 
I want to add auth to the application, after which users can create an account by logging in, creating their own notes which are private to them and can see their previously made notes.
Thanks

**Comment by BiswajitSahoo-tech** [comment]
Please assign this task to me

**Comment by abhinavkashyap061** [comment]
Hey @SujalSamai 👋, Thanks for considering contributing to my project

ok great! i am assigning you this one 👍

Happy Hacking 🚀
