### ISSUE TITLE
Fix the space between the text box and the add button in the mobile view 

### ISSUE THREAD

**Issue by Slmpire** [abhinavkashyap061/todolist#22]
@abhinavkashyap061 
#hacktoberfest

**Comment by abhinavkashyap061** [comment]
Hey @Slmpire  👋, Thanks for considering contributing to my project

- Okay , i am assigning you this task 👍

Happy Hacking 🚀

**Comment by Dhruvil-Lakhtaria** [comment]
Hey, I can also work on this. #hacktoberfest.
Can you assign this to me
