### ISSUE TITLE
Basic validation of tasks before adding

### ISSUE THREAD

**Issue by KarthikS373** [abhinavkashyap061/todolist#26]
It is noted that tasks can be added without typing anything in the task  field which leads to empty tasks
![image](https://user-images.githubusercontent.com/96634646/195012856-4b80fe41-1cc0-4a3e-b579-c21089219824.png)

Please assign this issue to me I would love to work over this...

**Comment by abhinavkashyap061** [comment]
Hey @KarthikS373   👋, Thanks for considering contributing to my project

- Okay , I am assigning you this task 👍

Happy Hacking 🚀

**Comment by KarthikS373** [comment]
Hey @abhinavkashyap061  I am having some trouble with setting up of the project. Can you please help me out regarding it.

I tried changing node version v14.20.1 as it was mentioned in the engine (also tried node v16.17.1)
Steps I did:
```Batchfile
  - npm install
  - npm start
```
(Also started my mongo server)

![Screenshot from 2022-10-13 19-14-22](https://user-images.githubusercontent.com/96634646/195614404-a77ddfc0-1436-447b-930c-9082b1056cde.png)

Still I didn't get the website up on port 8080 
can you please help out by stating out what I am missing??

Thanks in advance
