### ISSUE TITLE
Better Contributing.md file

### ISSUE THREAD

**Issue by YashM246** [abhinavkashyap061/todolist#28]

**Comment by YashM246** [comment]
Hey I would like to work on this. Could you assign this to me?

**Comment by abhinavkashyap061** [comment]
Hey @YashM246 👋, Thanks for considering contributing to my project

- please mention the improvements that you'll make in the existing readme

Happy Hacking 🚀

**Comment by YashM246** [comment]
I was thinking of adding some more steps and explaining it so that people who are new to Open Source Contributions and Hacktoberfest can better understand the procedure.

**Comment by abhinavkashyap061** [comment]
OK cool. I am assigning you this task!
