### ISSUE TITLE
ui bug in to-do list item text

### ISSUE THREAD

**Issue by abhinavkashyap061** [abhinavkashyap061/todolist#29]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/84775901/195129406-e359b56d-676d-474d-b5b1-32a175476365.png">

**Comment by Eddayavuz** [comment]
Hello, I can work on this.

**Comment by Adish90k** [comment]
can you assign this to me?

**Comment by abhinavkashyap061** [comment]
Hey @Eddayavuz   👋, Thanks for considering contributing to my project

- Okay , i am assigning you this task 👍

Happy Hacking 🚀
