### ISSUE TITLE
Add a footer 

### ISSUE THREAD

**Issue by aditi10701** [abhinavkashyap061/todolist#3]
a better version of the footer can be made. kindly assign me the same issue.

**Comment by PavvanPradeep** [comment]
can you assign this issue to me

**Comment by abhinavkashyap061** [comment]
Hey @PavvanPradeep @aditi10701  👋, Thanks for considering contributing to my project

please explain the changes proposed, and I will assign to the best ☺

Happy Hacking 🚀

**Comment by aditi10701** [comment]
I added a footer of this type. 
Various social media handle and a copyright section is added.
![image](https://user-images.githubusercontent.com/98349669/194718900-e9d5056c-a041-4458-b378-7d079107b9c0.png)

**Comment by aditi10701** [comment]
I added this footer with social media icons and a copyright.
Kindly consider this and assign this issue to me.![image](https://user-images.githubusercontent.com/98349669/194718943-9b380a91-6f1c-46b7-94c1-3e00056046d8.png)

**Comment by abhinavkashyap061** [comment]
Hey @aditi10701  👋, Thanks for considering contributing to my project

looks great, i am assigning you this issue. just match the color scheme and remove unnecessary links like Home, About, Partners, etc. below the icons. let there be just social media icons 👍

Happy Hacking 🚀

**Comment by aditi10701** [comment]
> Hey @aditi10701 👋, Thanks for considering contributing to my project
> 
> looks great, i am assigning you this issue. just match the color scheme and remove unnecessary links like Home, About, Partners, etc. below the icons. let there be just social media icons 👍
> 
> Happy Hacking 🚀

Sure!

**Comment by aditi10701** [comment]
The necessary changes are made . Should I generate a PR?
![image](https://user-images.githubusercontent.com/98349669/194720100-9cbd244a-a9b2-4c14-9c46-affd48892a2f.png)

**Comment by abhinavkashyap061** [comment]
yes, looks great!

**Comment by abhinavkashyap061** [comment]
Hey @aditi10701  👋

thanks for your valuable contribution!

Happy Hacking 🚀

**Comment by aditi10701** [comment]
This is showing as not accepted in hacktoberfest fest website . Can you let me know the reason?

**Comment by abhinavkashyap061** [comment]
can you send a screenshot?

**Comment by aditi10701** [comment]
![image](https://user-images.githubusercontent.com/98349669/194721436-852a8f6e-29af-46ab-b6d3-c181e53e48cd.png)

**Comment by abhinavkashyap061** [comment]
don't really have an idea what went wrong, I labeled everything as per the guidelines of Hacktoberfest though.

**Comment by aditi10701** [comment]
Please let me know what is needed to be done further I want my contribution to be counted as an successful PR.
