### ISSUE TITLE
Documentation issue in readme file

### ISSUE THREAD

**Issue by AnshuSarkarANX** [abhinavkashyap061/todolist#40]
- Need changes in the command of cloning the repo :
```diff
- git clone https://github.com/abhinavkashyap061/Dear-Diary.git
+ git clone https://github.com/abhinavkashyap061/todolist.git 
```

- Need changes in the command to enter into the local directory after cloning the repo : 
```diff
- cd Dear-Diary
+ cd todolist
```

**Comment by abhinavkashyap061** [comment]
wow even I didn't noticed that 😂. Ok I am assigning you this task!

**Comment by eddejayaklu** [comment]
I have raised one PR @abhinavkashyap061 closed without merging😢. Same thing I did, I have updated readme file.
