### ISSUE TITLE
add navbar

### ISSUE THREAD

**Issue by abhinavkashyap061** [abhinavkashyap061/todolist#48]
- I was thinking it would be better to have a navbar like we have in the blog app https://github.com/abhinavkashyap061/Dear-Diary . so taking contributions for that now
- I will be reviewing the PRs soon, I am caught up in deploying issues in https://todolist-abhinavkashyap061.herokuapp.com/  .
- I will not be taking contributions which will alter the whole folder structure like moving to MVC pattern.

**Comment by beheradibas** [comment]
I am taking a look and I would be making an MR. Assign me the issue, but it is not fixed by the time you want feel free to unassign.

**Comment by Krunal-Karena** [comment]
Please assign me this issue.
