### ISSUE TITLE
CSS Update

### ISSUE THREAD

**Issue by TheShonuff** [abhinavkashyap061/todolist#6]
I would like to contribute to this project by helping out with a little face lift.

**Comment by abhinavkashyap061** [comment]
Hey @TheShonuff 👋, Thanks for considering contributing to my project

Can you please tell the improvements that you will make in the styling of app 😅

Happy Hacking 🚀

**Comment by TheShonuff** [comment]
I would probably do everything.

Font change
Font sizing
Center the plus symbol in the add button
Round the edges
Adjust color scheme

To start

**Comment by TheShonuff** [comment]
@abhinavkashyap061 submitted a PR with screenshot of updated look

**Comment by abhinavkashyap061** [comment]
Hey @subrato3 👋

amazing changes mate!

Happy Hacking 🚀
